
# 1. Create vector with your raw column names 
col_names <- c(
  "PLAYER: player name",
  "ROLE: position/role",
  "NAT: nationality",
  "HEIGHT: height",
  "AGE: age on June 30 of the season end year",
  "TEAM: team name",
  "SEASON: season",
  "GP: games played",
  "W: wins",
  "L: losses",
  "MIN: minutes played",
  "PTS: points scored",
  "2PM: 2PT made",
  "2PA: 2PT attempted",
  "2P%: 2PT percentage",
  "3PM: 3PT made",
  "3PA: 3PT attempted",
  "3P%: 3PT percentage",
  "FGM: field goals made",
  "FGA: field goals attempted",
  "FG%: field goal percentage",
  "FTM: free throws made",
  "FTA: free throws attempted",
  "FT%: free throw percentage",
  "ORB: offensive rebounds",
  "DRB: defensive rebounds",
  "TRB: total rebounds",
  "AST: assists",
  "TOV: turnovers",
  "ST: steals",
  "BLK: blocks",
  "PF: personal fouls",
  "DF: fouls drawn",
  "+/-: plus/minus",
  "POSS: possessions played",
  "USG%: team played ended by the player | POSS / TM_ON_PLAYS",
  "PPP: points per possession | PTS / POSS",
  "TM OFF RTG (ON): team points per 100 poss with player ON | TM_ON_PTS / TM_ON_POSS × 100",
  "TM DEF RTG (ON): opponent points per 100 poss with player ON | OPP_ON_OPP_PTS / OPP_ON_OPP_POSS × 100",
  "TM NET RTG (ON): team net rating with player ON | TM OFF RTG (ON) − TM DEF RTG (ON)",
  "IND OFF RTG: individual offensive rating",
  "IND DEF RTG: individual defensive rating",
  "IND NET RTG: IND OFF RTG − IND DEF RTG",
  "eFG%: effective FG% | (2PM + 1.5 × 3PM) / FGA × 100",
  "TS%: true shooting percentage | PTS / (2 × (FGA + FTA2/2 + FTA3/3)) × 100",
  "RIM FREQ: rim attempt frequency | RIM_A / POSS × 100",
  "RIM PPS: points per rim attempt | RIM_M / RIM_A × 2",
  "PAINT FREQ: paint attempt frequency | PAINT_A / POSS × 100",
  "PAINT PPS: points per paint attempt | PAINT_M / PAINT_A × 2",
  "MID FREQ: mid-range attempt frequency | MID_A / POSS × 100",
  "MID PPS: points per mid-range attempt | MID_M / MID_A × 2",
  "C3 FREQ: corner-three frequency | C3_A / POSS × 100",
  "C3 PPS: points per corner three | C3_M / C3_A × 3",
  "L3 FREQ: above-the-break three frequency | L3_A / POSS × 100",
  "L3 PPS: points per above-the-break three | L3_M / L3_A × 3",
  "FT RATIO: free-throw rate | (FTA2/2 + FTA3/3) / POSS × 100",
  "TOV%: turnover percentage | TOV / POSS × 100",
  "LTOV%: live-ball turnover percentage | LTOV / POSS × 100",
  "DTOV%: dead-ball turnover percentage | DTOV / POSS × 100",
  "AST%: assist share of team scoring chances | AST / (...) × 100",
  "AST% (2P): assisted share of made 2PT",
  "AST% (3P): assisted share of made 3PT",
  "AST% (FT): assisted share of FT trips",
  "AST RATIO: assists per involvement | AST / (POSS + AST) × 100",
  "ORB%: offensive rebound percentage | ORB / (...) × 100",
  "DRB%: defensive rebound percentage | DRB / (...) × 100",
  "TRB%: total rebound percentage | TRB / (...) × 100",
  "ST%: steals per opponent possession | ST / OPP_ON_OPP_POSS × 100",
  "BLK%: blocks per opponent FGA | BLK / OPP_ON_OPP_FGA × 100",
  "PER: player efficiency rating",
  "OWS: offensive win share",
  "DWS: defensive win share",
  "WS: win share",
  "WS 40MIN: win share on 40 minutes",
  "OBPM: offensive box plus-minus",
  "DBPM: defensive box plus-minus",
  "BPM: box plus-minus",
  "VORP: value over replacement player",
  "FTA 2: FT attempts after a 2PT shooting foul (not and-one)",
  "FTA 3: FT attempts after a 3PT shooting foul (not and-one)",
  "FT 0/2: number of times a trip to the FT line ended with a 0/2",
  "FT 0/3: number of times a trip to the FT line ended with a 0/3",
  "LTOV: live-ball",
  "DTOV: dead-ball turnovers"
)

# 2. Remove everything after ":" → keep clean names only
library(stringr)
clean_names <- str_trim(str_remove(col_names, ":.*"))

# 3. Save as CSV
# Save cleaned names as a single header row
write.table(
  t(clean_names),                     # transpose so it's one row
  file = "clean_column_names.csv",
  sep = ",",
  col.names = FALSE,
  row.names = FALSE,
  quote = FALSE
)


